name: localquest
description: An application for fun quests in your local area.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


  flutter_map: ^8.2.2
  flutter_map_marker_cluster: ^8.2.2

  latlong2: ^0.9.1
  geolocator: ^14.0.2
  http: ^1.6.0

  animations: ^2.1.1
  material_design_icons_flutter: ^7.0.7296

  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
